import torch

# Learning
FEATURE_NUM = 7
TRAINING_EPOCHS = 5
LINEAR_BATCH_SIZE = 8
INITIAL_LEARNING_RATE = 0.05
MARGIN = 1.0

TURN_QUESTION_COEFF = 0.94
TURN_ANSWER_COEFF = 2.58
ENTITY_QUESTION_COEFF = 1.05
ENTITY_ANSWER_COEFF = 5.09
BASE_SCORE_COEFF = 0.39
TURN_PARSIMONY_COEFF = 0.89
ENTITY_PARSIMONY_COEFF = 1.46
MAX_RELEVANT_TURNS_OR_ENTITIES = 3

WIKI_PATTERN = "<en link=\"http://en.wikipedia.org/wiki/"
ENTITY_END_PATTERN = "\">"
TAG_END_PATTERN = "</en>"
ENTITY_PREFIX = "ENTITY/"
EPSILON = 1e-3
DEBUG = False
ENTITY_DIMENSION = 100
TOP_D = 300
TOP_S = 100
MIN_BASE_SCORE = -4.0

INV_SOFTPLUS_TEMP = 1.2471085395024732
SOFTPLUS_SCALE = 1.0
GUMBEL_BETA = 0.00036026463511690845
EULER_GAMMA = 0.57721566490153286060
TYPE_SIMILARITY_THRESHOLD = 0.5
MODEL_TYPE = "bert-large-uncased-whole-word-masking"
BOX_TYPE = "CenterSigmoidBoxTensor"
BOX_DIMENSION = 109
PROJECTION_LAYER = "highway"
PER_GPU_BATCH_SIZE = 8
TYPE_LIST_BATCH = 8
BOX_OFFSET = 0.5
NUMBER_OF_PROJECTION_LAYERS = 2
MAX_LEN = 512
BOX_TYPE_MODEL_PATH = "../data/resource/Box4Types/box_ufet.pt"
NUMBER_OF_TYPES = 10331
INIT_INTERVAL_DELTA = 0.5
INIT_INTERVAL_CENTER = 0.01
TYPE_FILE_PATH = "../data/resource/Box4Types/ufet_types.txt"
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Mention to entity data until 2017
MENTION_ENTITY_FILE_PATH = "../data/resource/WikipediaMention/mention-entity-freq.tsv.gz"
